name: "khe-renaissance"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=khe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d khe"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_internal

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/khe
      - ORIGIN=http://0.0.0.0:3000
    networks:
      - app_internal

networks:
  app_internal:
